SYMBOL = 'symbol'
ID = '_id'
OPEN_COL = '1  open'
HIGH_COL = '2  high'
LOW_COL = '3  low'
CLOSE_COL = '4  close'
ADJUSTED_CLOSE_COL = '5  adjusted close'
VOLUME_COL = '6  volume'
VOLUME_INTRADAY_COL = '5  volume'
DIVIDENT_AMOUNT_COL = '7  dividend amount'
SPLIT_COEFFICIENT_COL = '8  split coefficient'
LABEL_COL = 'Label'
FORECAST_DAYS = 1
LABEL_DISCRETE_COL = 'Label discrete'
FORECAST_FOR_TODAY_COL = 'Forecast for today'
FORECAST_FUTURE_COL = 'Forecast future'
FORECAST_PCT_CHANGE_COL = 'Forecast pct change'
FORECAST_DISCRETE_COL = 'Forecast discrete'
DAILY_PCT_CHANGE_COL = 'Daily pct change'
HL_PCT_CHANGE_COL = 'H/L pct change'
FALL_VALUE = -1
IDLE_VALUE = 0
RISE_VALUE = 1
TRESHOLD = 0.4
INDEX = 'index'
