SYMBOL = 'symbol'
ID = '_id'
OPEN_COL = '1  open'
HIGH_COL = '2  high'
LOW_COL = '3  low'
CLOSE_COL = '4  close'
ADJUSTED_CLOSE_COL = '5  adjusted close'
VOLUME_COL = '6  volume'
DIVIDENT_AMOUNT_COL = '7  dividend amount'
SPLIT_COEFFICIENT_COL = '8  split coefficient'
LABEL_COL = 'Label'
FORECAST_DAYS = 1
LABEL_DISCRETE_COL = 'Label discrete'
LABEL_BINARY_COL = 'Label binary'
DAILY_PCT_CHANGE_COL = 'Daily pct change'
HL_PCT_CHANGE_COL = 'H/L pct change'


SMA_5_COL = '5-SMA'
SMA_10_COL = '10-SMA'
SMA_20_COL = '20-SMA'
EMA_12_COL = '12-EMA'
EMA_26_COL = '26-EMA'
ROC_10_COL = '10-ROC'
TR_COL = 'TR' # true range
MOM_6_COL = '6-MOM' # true range
MOM_12_COL = '12-MOM' # true range
MACD_COL = 'MACD'
MACD_HIST_COL = 'MACD Hist'
MACD_SIGNAL_COL = 'MACD Signal'
STOCH_K_COL = 'STOCH SlowK'
STOCH_D_COL = 'STOCH SlowD'
RSI_6_COL = '6-RSI'
RSI_12_COL = '12-RSI'
APO_6_COL = '6-APO'
APO_12_COL = '12-APO'
WILLR_5_COL = '5-WILLR'
WILLR_10_COL = '10-WILLR'
BBANDS_10_RLB_COL = '10-BBANDS Real Lower Band'
BBANDS_20_RLB_COL = '20-BBANDS Real Lower Band'
BBANDS_10_RMB_COL = '10-BBANDS Real Middle Band'
BBANDS_20_RMB_COL = '20-BBANDS Real Middle Band'
BBANDS_10_RUB_COL = '10-BBANDS Real Upper Band'
BBANDS_20_RUB_COL = '20-BBANDS Real Upper Band'

FALL_VALUE = 0
IDLE_VALUE = 1
RISE_VALUE = 2
TRESHOLD = 0.4
INDEX = 'index'
