SYMBOL = 'symbol'
ID = '_id'
OPEN_COL = '1  open'
HIGH_COL = '2  high'
LOW_COL = '3  low'
CLOSE_COL = '4  close'
ADJUSTED_CLOSE_COL = '5  adjusted close'
VOLUME_COL = '6  volume'
DIVIDENT_AMOUNT_COL = '7  dividend amount'
SPLIT_COEFFICIENT_COL = '8  split coefficient'
LABEL_COL = 'Label'
FORECAST_DAYS = 1
LABEL_DISCRETE_COL = 'Label discrete'
LABEL_BINARY_COL = 'Label binary'
DAILY_PCT_CHANGE_COL = 'Daily pct change'
HL_PCT_CHANGE_COL = 'H/L pct change'

SMA_10_COL = '10-SMA'
SMA_20_COL = '20-SMA'
EMA_10_COL = '10-EMA'
EMA_20_COL = '20-EMA'
MACD_COL = 'MACD'
STOCH_COL = 'STOCH'
RSI_10_COL = '10-RSI'
RSI_20_COL = '20-RSI'
BBANDS_10_COL = '10-BBANDS'
BBANDS_20_COL = '20-BBANDS'

FALL_VALUE = 0
IDLE_VALUE = 1
RISE_VALUE = 2
TRESHOLD = 0.4
INDEX = 'index'
